language: ruby
rvm:
- 2.2.4
bundler_args: "--without production"
before_install:
- openssl aes-256-cbc -K $encrypted_5f77db495111_key -iv $encrypted_5f77db495111_iv
  -in .travis/deploy_key.enc -out .travis/deploy_key -d
install:
- bundle install
script:
- bundle exec rake test
addons:
  ssh_known_hosts:
  - sinnershiki.com:10022
deploy:
  skip_cleanup: true
  provider: script
  script: .travis/deploy.sh
  on:
    branch: master
