languege: ruby
rvm:
- 2.2.4
bundler_args: "--without production"
install:
- bundle install
script:
- bundle exec rake test
after_success:
- eval "$(ssh-agent -s)"
- chmod 600 .travis/deploy_key
- ssh-add .travis/deploy_key
- git remote add deploy ssh://sugano@sinnershiki.com:10022/home/sugano/portfolio.git
- git push deploy
before_install:
- openssl aes-256-cbc -K $encrypted_5f77db495111_key -iv $encrypted_5f77db495111_iv
  -in .travis/deploy_key.enc -out .travis/deploy_key -d
